# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Country.create(name: "mlb")
Country.create(name: "nfl")
Country.create(name: "nba")
Country.create(name: "nhl")



City.create(name: "Atlanta", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Arizona", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Baltimore", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Boston", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Chi White Sox", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Chi Cubs", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Cincinnati", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Cleveland", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Colorado", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Detroit", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Houston", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Kansas City", country_id: Country.find_by(name: "mlb").id)
City.create(name: "LA Angels", country_id: Country.find_by(name: "mlb").id)
City.create(name: "LA Dodgers", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Miami", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Milwaukee", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Minnesota", country_id: Country.find_by(name: "mlb").id)
City.create(name: "NY Mets", country_id: Country.find_by(name: "mlb").id)
City.create(name: "NY Yankees", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Oakland", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Philadelphia", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Pittsburgh", country_id: Country.find_by(name: "mlb").id)
City.create(name: "San Diego", country_id: Country.find_by(name: "mlb").id)
City.create(name: "San Francisco", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Seattle", country_id: Country.find_by(name: "mlb").id)
City.create(name: "St. Louis", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Tampa Bay", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Texas", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Toronto", country_id: Country.find_by(name: "mlb").id)
City.create(name: "Washington", country_id: Country.find_by(name: "mlb").id)

City.create(name: "Arizona Cardinals", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Atlanta Falcons", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Baltimore Ravens", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Buffalo Bills", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Carolina Panthers", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Chicago Bears", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Cincinnati Bengals", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Cleveland Browns", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Dallas Cowboys", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Denver Broncos", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Detroit Lions", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Green Bay Packers", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Houston Texans", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Indiannapolis Colts", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Jacksonville Jaguars", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Kansas City Chiefs", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Miami Dolphins", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Minnesota Vikings", country_id: Country.find_by(name: "nfl").id)
City.create(name: "New England Patriots", country_id: Country.find_by(name: "nfl").id)
City.create(name: "New Orleans Saints", country_id: Country.find_by(name: "nfl").id)
City.create(name: "NY Giants", country_id: Country.find_by(name: "nfl").id)
City.create(name: "NY Jets", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Oakland Raiders", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Philadelphia Eagles", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Pittsburgh Steelers", country_id: Country.find_by(name: "nfl").id)
City.create(name: "San Diego Chargers", country_id: Country.find_by(name: "nfl").id)
City.create(name: "San Francisco 49ers", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Seattle Seahawks", country_id: Country.find_by(name: "nfl").id)
City.create(name: "St. Louis Rams", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Tampa Bay Buccaneers", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Tennessee Titans", country_id: Country.find_by(name: "nfl").id)
City.create(name: "Washington Redskins", country_id: Country.find_by(name: "nfl").id)

City.create(name: "Tennessee Titans", country_id: Country.find_by(name: "nba").id)
City.create(name: "Washington Redskins", country_id: Country.find_by(name: "nba").id)

City.create(name: "Tennessee Titans", country_id: Country.find_by(name: "nhl").id)
City.create(name: "Washington Redskins", country_id: Country.find_by(name: "nhl").id)
